missing_base_fields = "Missing base L-System configuration field(s) required for instantiation."
invalid_vars_type = "L-System typing of variables in configuration file invalid. Expected 'list' of 'string' entries."
invalid_const_type = "L-System typing of constants in configuration file invalid. Expected 'list' of 'string' entries."
invalid_axiom_type = "L-System typing of axiom invalid. Expected 'string'."
invalid_rules_type = "L-System typing of rules in configuration file invalid."
lsys_missing_variable = "L-System missing at least one variable defined in variables."
axiom_missing_variable = "Axiom missing at least one variable defined in variables."
axiom_undefined_symbol = "Axiom with undefined symbol."
rules_false_one_to_one_correspondence_with_vars = "Rule variables must have one-to-one correspondence with defined variables"
rules_undefined_output_symbol = "Rule(s) with output of which symbols are undefined"
vars_const_intersection = "Variables and constants share common symbol(s)."

missing_draw_fields = "Missing required L-System configuration field(s) for drawing."
invalid_translations_type = "L-System typing of translations in configuration file invalid. Expected 'dict' with 'string' pairs."
invalid_length_value = "L-System configuration file invalid length value. Expected numeric value."
invalid_angle_value = "L-System configuration file invalid angle value. Expected numeric value."
translations_false_one_to_one_correspondence_with_vars_and_consts = "Translation symbols must have one-to-one correspondence with defined variables and defined constants"
unsupported_translations = "L-System includes unsupported translation."