MISSING_BASE_FIELDS = "Missing base L-System configuration field(s) required for instantiation."
INVALID_VARIABLES_TYPE = "Invalid L-System variables type. Expected 'list' of 'string' entries"
INVALID_CONSTANTS_TYPE = "Invalid L-System constants type. Expected 'list' of 'string' entries"
INVALID_AXIOM_TYPE = "Invalid L-System axiom type. Expected 'string'"
INVALID_RULES_TYPE = "Invalid L-System rules type. Expected 'dict' with string:string or string:list(float, int) key-value pairs."
MISSING_VARIABLE = "Missing at least one defined variable in L-System variables."
AXIOM_UNDEFINED_SYMBOL = "Undefined symbol in L-System axiom."
AXIOM_MISSING_VARIABLE = "Missing at least one defined variable from L-System variables in L-System axiom."
RULES_VARIABLES_MISMATCH = "False one-to-one correspondence between L-System rule keys and L-System variables."
RULES_UNDEFINED_REPRODUCTION = "Undefined symbol in L-System rule reproduction values."
VARIABLES_CONSTANTS_OVERLAP = "L-System variables and L-System constants share common symbol"

INVALID_TRANSLATIONS_TYPE = "Invalid L-System translations type. Expected 'dict' with string:string key-value pairs."
TRANSLATIONS_ALPHABET_MISMATCH = "False one-to-one correspondence between L-System translation keys and L-System alphabet."
UNSUPPORTED_TRANSLATION = "Unsupported translation"
INVALID_WIDTH_TYPE = "Invalid L-System width. Expected positive integer value."